import type { SelectOption } from "./runFormOptions";

export const CATEGORY_OPTIONS: SelectOption[] = [
  { value: "Abandoned Places", label: "Abandoned Places" },
  { value: "Adventure", label: "Adventure" },
  { value: "Animals", label: "Animals" },
  { value: "Animations", label: "Animations" },
  { value: "Anime", label: "Anime" },
  { value: "Art", label: "Art" },
  { value: "ASMR", label: "ASMR" },
  { value: "Astrology", label: "Astrology" },
  { value: "Aviation", label: "Aviation" },
  { value: "Books", label: "Books" },
  { value: "Budgeting", label: "Budgeting" },
  { value: "Cars", label: "Cars" },
  { value: "Chess", label: "Chess" },
  { value: "Commentary", label: "Commentary" },
  { value: "Conspiracy", label: "Conspiracy" },
  { value: "Construction", label: "Construction" },
  { value: "Cosplay", label: "Cosplay" },
  { value: "Crimes", label: "Crimes" },
  { value: "Cybersecurity", label: "Cybersecurity" },
  { value: "Cycling", label: "Cycling" },
  { value: "Dance", label: "Dance" },
  { value: "DIY", label: "DIY" },
  { value: "Documentary", label: "Documentary" },
  { value: "Editing", label: "Editing" },
  { value: "Education", label: "Education" },
  { value: "Engineering", label: "Engineering" },
  { value: "Entertainment", label: "Entertainment" },
  { value: "Environment", label: "Environment" },
  { value: "Family", label: "Family" },
  { value: "Fashion", label: "Fashion" },
  { value: "Finance", label: "Finance" },
  { value: "Fishing", label: "Fishing" },
  { value: "Fitness", label: "Fitness" },
  { value: "Food", label: "Food" },
  { value: "Football", label: "Football" },
  { value: "Gaming", label: "Gaming" },
  { value: "Guitars", label: "Guitars" },
  { value: "Health", label: "Health" },
  { value: "History", label: "History" },
  { value: "Home Decor", label: "Home Decor" },
  { value: "Home Renovation", label: "Home Renovation" },
  { value: "Humor", label: "Humor" },
  { value: "Hunting", label: "Hunting" },
  { value: "Infotainment", label: "Infotainment" },
  { value: "Interview", label: "Interview" },
  { value: "Journalism", label: "Journalism" },
  { value: "Just Chatting", label: "Just Chatting" },
  { value: "Kids", label: "Kids" },
  { value: "Lego", label: "Lego" },
  { value: "Lifestyle", label: "Lifestyle" },
  { value: "Minecraft", label: "Minecraft" },
  { value: "Motivation", label: "Motivation" },
  { value: "Movies", label: "Movies" },
  { value: "Music", label: "Music" },
  { value: "Mystery", label: "Mystery" },
  { value: "News", label: "News" },
  { value: "Outdoor", label: "Outdoor" },
  { value: "Painting", label: "Painting" },
  { value: "Parenting", label: "Parenting" },
  { value: "Pets", label: "Pets" },
  { value: "Photography", label: "Photography" },
  { value: "Plants", label: "Plants" },
  { value: "Podcast", label: "Podcast" },
  { value: "Pokemon Cards", label: "Pokemon Cards" },
  { value: "Politics", label: "Politics" },
  { value: "Pop Culture", label: "Pop Culture" },
  { value: "Reviews", label: "Reviews" },
  { value: "Science", label: "Science" },
  { value: "Society", label: "Society" },
  { value: "Sport", label: "Sport" },
  { value: "TCG", label: "TCG" },
  { value: "Tech", label: "Tech" },
  { value: "Travel", label: "Travel" },
  { value: "Variety", label: "Variety" },
  { value: "Vlog", label: "Vlog" },
  { value: "Yoga", label: "Yoga" }
];

export const TYPE_OPTIONS: SelectOption[] = [
  { value: "Male", label: "Male" },
  { value: "Female", label: "Female" },
  { value: "Couple", label: "Couple" },
  { value: "Family", label: "Family" },
  { value: "Team", label: "Team" },
  { value: "Animation", label: "Animation" },
  { value: "Kids", label: "Kids" },
  { value: "Faceless", label: "Faceless" }
];
