export type SelectOption = {
  value: string;
  label: string;
};

export const KEYWORD_OPTIONS: SelectOption[] = [
  { value: "beauty", label: "Beauty" },
  { value: "business", label: "Business" },
  { value: "cars", label: "Cars" },
  { value: "comedy", label: "Comedy" },
  { value: "cooking", label: "Cooking" },
  { value: "education", label: "Education" },
  { value: "fashion", label: "Fashion" },
  { value: "finance", label: "Finance" },
  { value: "fitness", label: "Fitness" },
  { value: "food", label: "Food" },
  { value: "gaming", label: "Gaming" },
  { value: "health", label: "Health" },
  { value: "home decor", label: "Home Decor" },
  { value: "lifestyle", label: "Lifestyle" },
  { value: "luxury", label: "Luxury" },
  { value: "music", label: "Music" },
  { value: "parenting", label: "Parenting" },
  { value: "pets", label: "Pets" },
  { value: "photography", label: "Photography" },
  { value: "podcasts", label: "Podcasts" },
  { value: "productivity", label: "Productivity" },
  { value: "sports", label: "Sports" },
  { value: "technology", label: "Technology" },
  { value: "travel", label: "Travel" },
];

export const COUNTRY_OPTIONS: SelectOption[] = [
  { value: "AE", label: "United Arab Emirates" },
  { value: "AR", label: "Argentina" },
  { value: "AT", label: "Austria" },
  { value: "AU", label: "Australia" },
  { value: "BE", label: "Belgium" },
  { value: "BG", label: "Bulgaria" },
  { value: "BR", label: "Brazil" },
  { value: "CA", label: "Canada" },
  { value: "CH", label: "Switzerland" },
  { value: "CL", label: "Chile" },
  { value: "CO", label: "Colombia" },
  { value: "CZ", label: "Czechia" },
  { value: "DE", label: "Germany" },
  { value: "DK", label: "Denmark" },
  { value: "EE", label: "Estonia" },
  { value: "EG", label: "Egypt" },
  { value: "ES", label: "Spain" },
  { value: "FI", label: "Finland" },
  { value: "FR", label: "France" },
  { value: "GB", label: "United Kingdom" },
  { value: "GR", label: "Greece" },
  { value: "HK", label: "Hong Kong" },
  { value: "HR", label: "Croatia" },
  { value: "HU", label: "Hungary" },
  { value: "ID", label: "Indonesia" },
  { value: "IE", label: "Ireland" },
  { value: "IL", label: "Israel" },
  { value: "IN", label: "India" },
  { value: "IT", label: "Italy" },
  { value: "JP", label: "Japan" },
  { value: "KR", label: "South Korea" },
  { value: "LT", label: "Lithuania" },
  { value: "LV", label: "Latvia" },
  { value: "MX", label: "Mexico" },
  { value: "MY", label: "Malaysia" },
  { value: "NL", label: "Netherlands" },
  { value: "NO", label: "Norway" },
  { value: "NZ", label: "New Zealand" },
  { value: "PE", label: "Peru" },
  { value: "PH", label: "Philippines" },
  { value: "PL", label: "Poland" },
  { value: "PT", label: "Portugal" },
  { value: "RO", label: "Romania" },
  { value: "RS", label: "Serbia" },
  { value: "SA", label: "Saudi Arabia" },
  { value: "SE", label: "Sweden" },
  { value: "SG", label: "Singapore" },
  { value: "SI", label: "Slovenia" },
  { value: "SK", label: "Slovakia" },
  { value: "TH", label: "Thailand" },
  { value: "TR", label: "Turkey" },
  { value: "TW", label: "Taiwan" },
  { value: "UA", label: "Ukraine" },
  { value: "US", label: "United States" },
  { value: "VN", label: "Vietnam" },
  { value: "ZA", label: "South Africa" },
];

export const LANGUAGE_OPTIONS: SelectOption[] = [
  { value: "ar", label: "Arabic" },
  { value: "bg", label: "Bulgarian" },
  { value: "cs", label: "Czech" },
  { value: "da", label: "Danish" },
  { value: "de", label: "German" },
  { value: "el", label: "Greek" },
  { value: "en", label: "English" },
  { value: "es", label: "Spanish" },
  { value: "fi", label: "Finnish" },
  { value: "fr", label: "French" },
  { value: "he", label: "Hebrew" },
  { value: "hi", label: "Hindi" },
  { value: "hr", label: "Croatian" },
  { value: "hu", label: "Hungarian" },
  { value: "id", label: "Indonesian" },
  { value: "it", label: "Italian" },
  { value: "ja", label: "Japanese" },
  { value: "ko", label: "Korean" },
  { value: "ms", label: "Malay" },
  { value: "nl", label: "Dutch" },
  { value: "no", label: "Norwegian" },
  { value: "pl", label: "Polish" },
  { value: "pt", label: "Portuguese" },
  { value: "ro", label: "Romanian" },
  { value: "ru", label: "Russian" },
  { value: "sk", label: "Slovak" },
  { value: "sl", label: "Slovenian" },
  { value: "sv", label: "Swedish" },
  { value: "th", label: "Thai" },
  { value: "tr", label: "Turkish" },
  { value: "uk", label: "Ukrainian" },
  { value: "vi", label: "Vietnamese" },
  { value: "zh", label: "Chinese" },
];
